### PR TITLE
Add feature for syslog5

### LINKED ISSUE #47: Add feature for syslog 5
Should be fairly straightforward, we can do the same thing we did for the syslog3/4 distinction for adding support for syslog 5. Main work is in rewriting full examples to use syslog 5.

There were some things that syslog 3 could do, but syslog 4 couldn't. I can't remember off the top of my head what they were. If syslog 5 fixes these, and is at least as capable as both syslog 3 and 4, we can remove syslog 3/4 examples and leave only actual library code, replacing them entirely with syslog 5 examples.

### PR DESCRIPTION
**Pull request by Cogitri**
fixes #47

Tested this on a project of mine and changing it was as easy as changing the version

### CODE REVIEW

**Comment by daboross** [comment]
Hi - thank you for doing this! I'm afraid actually updating it needs to be a bit more complicated, though.

If we just remove support for `syslog` version 4, that means anyone currently depending on `fern` and `syslog` v4.0 would have their build broken. And thus to keep compatibility guarantees, we'd need to release a new major version of `fern`. Since it's just a dependency update, I'd rather not do that.

So, to keep it compatible, we'll need to keep both `syslog-4` and `syslog-5` features concurrently. I'd be happy to remove `syslog-4` support in the next major version release, but that should wait until `fern` actually has breaking changes to make itself.

**Comment by Cogitri** [comment]
Oh fair, I didn't consider that that'd require a minor version bump. I'll try to look into fixing this in the next week or so, thanks for taking a look

**Comment by Cogitri** [comment]
I've re-added the syslog4 feature.

BTW, now that https://github.com/Geal/rust-syslog/issues/41 is fixed in syslog v5, do we to do something additional in fern to avoid allocations?

**Comment by Cogitri** [comment]
Hm, the `--all-features` test run fails on travis because syslog-4 and syslog-5 have some duplicate definitions, not sure how we best handle that

**Comment by Roguelazer** [comment]
Any way we can help move this forward? I would very much like this feature.

**Comment by Roguelazer** [comment]
bump

**Comment by Roguelazer** [comment]
I added syslog 6 support in #91

**Comment by Cogitri** [comment]
Sure, let me close this

**Pull request closed without merging**
