### PR TITLE
Prevent deadlocking on files when formatting itself is logged.

### PR DESCRIPTION
**Pull request by jakunar**
Hi,
first of all, thanks for the great library. Really nice and intuitive to use.

I ran into a deadlock, when the formatting of my initial log caused another log.
Not sure if the way I fixed it is ideal since it reverses the order of the logs, but at least there is no deadlock.

### CODE REVIEW

**Comment by daboross** [comment]
Thank you for the patch!

This isn't at all something I had considered, but you're right, this will definitely cause deadlocks.

Ideally I'd like to keep the main logging path allocation-free, but it might not be possible to do that. Right now, everything can be purely on the stack from the log call to the file write, but a `format!()` call would require allocating a new String.

Not that fern needs to be that performance oriented. I try to keep to "the most obvious usage of a library should be the fastest one", but if this is the best solution, I'm good with it.

---

The one other possibility I can think of may or may not be better. If we could detect when a mutex is locked from the current thread, we could potentially set a flag and then stick further logging results into a `VecDeque`. `VecDeque`, like `Vec`, won't really take up memory until the first time it's used, so this would have a minimal impact on regular logging, and would only need to kick in if there's logging within a logging call.

Thoughts on an auxiliary queue vs. using `format!()` every call?

**Comment by daboross** [comment]
If it turns out impossible or too complicated to detect which thread a Mutex is locked from, I'll merge this as is and just update the documentation to remove the "allocation free" claim.

**Comment by jakunar** [comment]
You could add a feature, say 'stateful-file-logging', which conditionally prevents this deadlock.
This would let fern stay "allocation free" unless you request otherwise.

An example implementation would be in my fork at branch 'stateful-file-log'.
The diff would be here:
https://github.com/daboross/fern/compare/master...jakunar:stateful-file-log
Apart from inside Cargo.toml I did not add or modify any documentation, that would be up to you.

Not sure how Github works from yourside, could you just pull and merge it, or would it be easier if a made another PR?

**Comment by daboross** [comment]
That would definitely be a possibility! I'd be somewhat hesitant to put a change in behavior like this in an additive feature flag, but it would probably be fine.

The only reason we might want a separate configuration option is so that there could still be separate faster formatting, and so that this could be a `format!()` at the dispatch level rather than per-File. The advantage of having it on Dispatch would be in never duplicating callback calls. (if there was a Dispatch with two File children, you'd have double the logs in the Dispatch formatter, I think we want to avoid this?)

If we add `stateful` as a flag on `Dispatch` instead, `format!()` could reasonably be done within each Dispatch which had this set. I wouldn't want to do it on every dispatch via a feature flag because it would decrease chained dispatch performance with very little advantage.

I guess if we're fixing this, I would also want predictable behavior when logging within formatting callbacks.

In my opinion, something like this:

```rust
Dispatch::new()
    .format(|out, message, _| {
        if message[0] == 'h' {
            info!("just logged something");
        }
        out.finish(format_args!("{}", message))
    })
    .stateful_format(true)
    .chain(std::io::stdout())
    .chain(fern::log_file("output.log")?)
    .apply()?;
info!("hello, world.");
```

should log this:
```
hello, world.
just logged something.
```
not this:
```
hello, world.
just logged something.
just logged something.
```

**Comment by daboross** [comment]
Sorry about posting that prematurely. Just edited my last comment a ton for clarity.

**Comment by daboross** [comment]
I've been considering this, and I think your original solution is really the best one we have for now.

The alternate one posted might be lead to more performance, but it also has the one race condition right now, and the benefits might be negligible.

I'm going to merge this, then apply the same change to Stdout and Stderr loggers which suffer from the same problem.

Thank you for doing this!

**Comment by daboross** [comment]
@jakunar Sorry, one more question if you're available:

When writing a test case for this, I realized the problem was not as widespread as I thought. We can still include a feature, but this will change how it's documented.

I don't think the file should be locked in any case _when the formatting callback is called_, only when the `format_args!()` is evaluated.

Does switching your specific case to something like this work for you on the released `fern` version?

```rust
// rather than
out.finish(format_args!(
    "[{}]{} {}",
    // This will color the log level only, not the whole line. Just a touch.
    record.level(),
    chrono::Utc::now().format("[%Y-%m-%d %H:%M:%S]"),
    message
))
// it would be:
let formatted = format!(
    "[{}]{} {}",
    // This will color the log level only, not the whole line. Just a touch.
    record.level(),
    chrono::Utc::now().format("[%Y-%m-%d %H:%M:%S]"),
    message
);
out.finish(format_args!("{}", formatted))
```

**Comment by daboross** [comment]
Published in 0.5.3.

**Pull request merged**
